@startuml TinyTasks
left to right direction

!define include "<<include>>"
!define extends "<<extends>>"

actor user as "User" <<Human>>
actor system as "System" <<Application>>

note bottom of system 
might be the operating system or
any other case where no user
is explicitly involved
end note

rectangle UserInterface {
    usecase create as "
        create worker
    "
    usecase delete as "
        delete worker
    "
    usecase change as "
        change worker preferences
    "
    usecase save as "
        save workers
    " 
    
    delete ..> create : include
    change ..> create : include
}

note right of save
    This is explicitly asked if
    the form is closed by the user
end note

rectangle Service {
    usecase start as "
        start workers
    "
    usecase abort as "
        abort workers
    "

    abort .> start : extends
}

note right of abort
    1. stop each running worker
    2. save workers into configuration
end note

note right of start
    1. load workers from configuration
    2. start each loaded worker
end note

system --> start
system --> abort

user --> start
user --> abort
user --> save

user -> create
user -> delete
user -> change

@enduml