@startuml Usecases
left to right direction

!define include "<<include>>"

actor user as "User"
actor system as "System"

note right of system : might be the operating system

rectangle UserInterface {
    usecase open as "
    1.1 Open
    graphical user interface
    "
    usecase exit as "
    1.3 Exit
    graphical user interface
    "
    user --> open
    user --> exit

    rectangle Configuration {
        usecase manage as "
        1.2 Manage
        configuration
        "
    }
    user --> manage
}

rectangle Application {
    usecase start as "
    2.1 Start
    application
    "
    usecase abort as "
    2.2 Abort
    application
    "
}

user --> start
user --> abort

system --> start
system --> abort

@enduml