@startuml TinyTasks

object Program {
	configuration = "xyz/TinyTasks.cache"
}

object "<u>manager : Workers</u>" as manager {
	configuration = "xyz/TinyTasks.cache"
}

object "<u>workerAlpha : SyncWorker</u>" as workerAlpha {
	group = 548ea2cb-b9db-465f-8228-4ad09466ec53
	label = 937192c9-f4e9-4a1c-81dc-3f41282f2c7e
}

object "<u>workerGamma : SyncWorker</u>" as workerGamma {
	group = 548ea2cb-b9db-465f-8228-4ad09466ec53
	label = 67a9b1c9-18fe-4c40-ac49-5e91e1c0ea1d
}

object "<u>workers : Dictionary</u>" as workers {
	...
}

object "<u>setAlpha : PreferenceSet</u>" as preferenceAlpha
object "<u>setGamma : PreferenceSet</u>" as preferenceGamma

object "<u>sourceAlpha : ScalarPreference</u>" as sourceAlpha {
	Name = "source"
	Value = ""
	Visible = true
}

object "<u>targetAlpha : ScalarPreference</u>" as targetAlpha {
	Name = "target"
	Value = ""
	Visible = true
}

object "<u>sourceGamma : ScalarPreference</u>" as sourceGamma {
	Name = "source"
	Value = ""
	Visible = true
}

object "<u>targetGamma : ScalarPreference</u>" as targetGamma {
	Name = "target"
	Value = ""
	Visible = true
}

Program -- manager : manager
Program -- workers : workers

workers o-- workerAlpha : content
workers o-- workerGamma : content

workerAlpha -- preferenceAlpha : Preferences
preferenceAlpha o-- sourceAlpha 
preferenceAlpha o-- targetAlpha 
workerAlpha -- sourceAlpha : source
workerAlpha -- targetAlpha : target

workerGamma -- preferenceGamma : Preferences
preferenceGamma o-- sourceGamma
preferenceGamma o-- targetGamma
workerGamma -- sourceGamma : source
workerGamma -- targetGamma : target
@enduml
