@startuml
class DictionaryPreferenceProvider {
    - <<readonly>> preferences : IDictionary
    + DictionaryPreferenceProvider(map:IDictionary)
}
IPreferenceProvider <|.. DictionaryPreferenceProvider
@enduml
