@startuml
class PreferenceSet {
    - {static} <<readonly>> Formatter : IFormatter
    - derivations : IDictionary
    - preferences : IDictionary
    - provider : IPreferenceProvider
    + PreferenceSet()
    + {static} IsNullOrTypeDefault(value:T) : bool
    - HasPreferenceCache(name:string, preference:ScalarPreference<T>) : bool
    - HasPreferenceListCache(name:string, preference:ListPreference<T>) : bool
    + Preference(name:string, value:T) : ScalarPreference<T>
    + ListPreference(name:string, values:IList<T>) : ListPreference<T>
    + GetAll() : IEnumerable<IPreference>
    + GetVisible() : IEnumerable<IPreference>
    + Load(stream:Stream) : void
    + Save(stream:Stream) : void
}
@enduml
