@startuml
class "Preference"<T> {
    - <<readonly>> provider : IPreferenceProvider
    + Preference(preferences:IPreferenceProvider, name:string, value:T)
    + HasDefaultValue : bool <<get>>
    + IsHidden : bool <<get>>
    + Name : string <<get>>
    + Value : T <<get>> <<set>>
    - {static} IsDefaultOrNull(value:TV) : bool
    + MakeHidden() : Preference<T>
}
@enduml
