@startuml
class "ScalarPreference"<T> {
    - <<readonly>> provider : IPreferenceProvider
    + ScalarPreference(preferences:IPreferenceProvider, name:string, value:T)
    + DataType : PreferenceDataType <<get>>
    + Visible : bool <<get>> = true
    + HasDefaultValue : bool <<get>>
    + HasValueSet : bool <<get>>
    + Complete : bool <<get>>
    + Name : string <<get>>
    + Value : T <<get>> <<set>>
    + ValueType : Type <<get>>
    + ToView() : string
    + FromView(line:string) : void
    + ToggleVisibility() : ScalarPreference<T>
    + UpdateDataType(dataType:PreferenceDataType) : ScalarPreference<T>
    - {static} TryParseValue(input:string, result:TTo) : bool
}
IPreference <|.. "ScalarPreference"
@enduml
