@startuml
class Parameters <<partial>> {
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - Group : System.Windows.Forms.Label
    - Label : System.Windows.Forms.Label
    - Options : System.Windows.Forms.DataGridView
    - OptionsGridLabel : System.Windows.Forms.DataGridViewTextBoxColumn
    - OptionsGridValue : System.Windows.Forms.DataGridViewTextBoxColumn
    - Okay : System.Windows.Forms.Button
    - Cancel : System.Windows.Forms.Button
}
@enduml
