@startuml
class Dashboard <<partial>> {
    - components : System.ComponentModel.IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - overview : System.Windows.Forms.DataGridView
    - overviewLabel : System.Windows.Forms.DataGridViewTextBoxColumn
    - overviewGroup : System.Windows.Forms.DataGridViewTextBoxColumn
    - overviewObject : System.Windows.Forms.DataGridViewTextBoxColumn
}
@enduml
