@startuml
class Dashboard <<partial>> {
    - <<readonly>> manager : Workers
    - <<readonly>> workers : IDictionary<Guid, IWorker>
    + Dashboard()
    - {static} GetDefaultConfiguration() : string
    - {static} InitializeLogger() : void
    - {static} HandleLoggerMessage(message:string) : void
    - LoadWorkers() : void
    - SaveWorkers() : void
    - ViewRefresh() : void
    - ShowWorker(worker:IWorker) : void
    - OnFormLoading(sender:object, args:EventArgs) : void
    - OnFormClosing(sender:object, args:FormClosingEventArgs) : void
    - OnCellClick(sender:object, args:DataGridViewCellEventArgs) : void
    - {static} DialogWorkerType(group:Guid, label:Guid) : bool
}
@enduml
