@startuml
class Parameters <<partial>> {
    - components : IContainer = null
    # <<override>> Dispose(disposing:bool) : void
    - InitializeComponent() : void
    - labelGroup : System.Windows.Forms.Label
    - labelLabel : System.Windows.Forms.Label
    - options : System.Windows.Forms.DataGridView
    - optionsObject : System.Windows.Forms.DataGridViewTextBoxColumn
    - optionsLabel : System.Windows.Forms.DataGridViewTextBoxColumn
    - optionsValue : System.Windows.Forms.DataGridViewTextBoxColumn
    - controlOkay : System.Windows.Forms.Button
    - controlCancel : System.Windows.Forms.Button
}
@enduml
